# Generated by Django 3.2.11 on 2022-01-30 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CustomerDemographics',
            fields=[
                ('customer_type_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('customer_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_demographics',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('fax', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('title_of_courtesy', models.CharField(blank=True, max_length=25, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=24, null=True)),
                ('extension', models.CharField(blank=True, max_length=4, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('reports_to', models.ForeignKey(blank=True, db_column='reports_to', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employees')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='GeographyColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_table_catalog', models.TextField(blank=True, null=True)),
                ('f_table_schema', models.TextField(blank=True, null=True)),
                ('f_table_name', models.TextField(blank=True, null=True)),
                ('f_geography_column', models.TextField(blank=True, null=True)),
                ('coord_dimension', models.BigIntegerField(blank=True, null=True)),
                ('srid', models.BigIntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geography_columns',
            },
        ),
        migrations.CreateModel(
            name='GeometryColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_table_catalog', models.TextField(blank=True, null=True)),
                ('f_table_schema', models.TextField(blank=True, null=True)),
                ('f_table_name', models.TextField(blank=True, null=True)),
                ('f_geometry_column', models.TextField(blank=True, null=True)),
                ('coord_dimension', models.BigIntegerField(blank=True, null=True)),
                ('srid', models.BigIntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geometry_columns',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('region_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('shipper_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'shippers',
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srid', models.BigIntegerField(blank=True, null=True)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.BigIntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_title', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('fax', models.CharField(blank=True, max_length=24, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='UsStates',
            fields=[
                ('state_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state_abbr', models.CharField(blank=True, max_length=2, null=True)),
                ('state_region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'us_states',
            },
        ),
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('territory_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('territory_description', models.CharField(max_length=200)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.region')),
            ],
            options={
                'db_table': 'territories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('quantity_per_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('units_in_stock', models.SmallIntegerField(blank=True, null=True)),
                ('units_on_order', models.SmallIntegerField(blank=True, null=True)),
                ('reorder_level', models.SmallIntegerField(blank=True, null=True)),
                ('discontinued', models.BigIntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.categories')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.suppliers')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('freight', models.FloatField(blank=True, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=40, null=True)),
                ('ship_address', models.CharField(blank=True, max_length=60, null=True)),
                ('ship_city', models.CharField(blank=True, max_length=15, null=True)),
                ('ship_region', models.CharField(blank=True, max_length=15, null=True)),
                ('ship_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ship_country', models.CharField(blank=True, max_length=15, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customers')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employees')),
                ('ship_via', models.ForeignKey(blank=True, db_column='ship_via', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.shippers')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crm.orders')),
                ('unit_price', models.FloatField()),
                ('quantity', models.SmallIntegerField()),
                ('discount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.products')),
            ],
            options={
                'db_table': 'order_details',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeTerritories',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crm.employees')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.territories')),
            ],
            options={
                'db_table': 'employee_territories',
                'unique_together': {('employee', 'territory')},
            },
        ),
        migrations.CreateModel(
            name='CustomerCustomerDemo',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crm.customers')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customerdemographics')),
            ],
            options={
                'db_table': 'customer_customer_demo',
                'unique_together': {('customer', 'customer_type')},
            },
        ),
    ]
